# PostgreSQL. Versions 9.1 and up are supported.
#
defaults_pg: &defaults_pg
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:

test:
  <<: *defaults_pg
  database: ea2_V2_test<%= ENV['TEST_ENV_NUMBER'] %>

development:
  <<: *defaults_pg
  database: ea2_V2_development

production:
  url: <%= ENV[‘DATABASE_URL’] %>

staging:
 url: <%= ENV[‘DATABASE_URL’] %>
