# PostgreSQL. Versions 9.1 and up are supported.
#
defaults_pg: &defaults_pg
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:

test:
  <<: *defaults_pg
  database: ea2_V2_test<%= ENV['TEST_ENV_NUMBER'] %>

development:
  <<: *defaults_pg
  database: ea2_V2_development

production:
  <<: *defaults_pg
  database: ea2_V2_production
  username: ea2_V2
  password: <%= ENV['ea2_V2_DATABASE_PASSWORD'] %>
